// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBJhl5gSaFxHugmZeBPgM9lirlFK_pBxk',
    appId: '1:512210715188:web:fda56645c3177e8b3b4061',
    messagingSenderId: '512210715188',
    projectId: 'e-commerce-3d201',
    authDomain: 'e-commerce-3d201.firebaseapp.com',
    storageBucket: 'e-commerce-3d201.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYdeXLIHTvfY-XRIiiytrL-uCzN6TYhr4',
    appId: '1:512210715188:android:f5cd983adb6126b13b4061',
    messagingSenderId: '512210715188',
    projectId: 'e-commerce-3d201',
    storageBucket: 'e-commerce-3d201.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn7op_sn7ogycp8OaIojI6z8r0-Qt7QbQ',
    appId: '1:512210715188:ios:425c2a7583eadaa23b4061',
    messagingSenderId: '512210715188',
    projectId: 'e-commerce-3d201',
    storageBucket: 'e-commerce-3d201.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn7op_sn7ogycp8OaIojI6z8r0-Qt7QbQ',
    appId: '1:512210715188:ios:425c2a7583eadaa23b4061',
    messagingSenderId: '512210715188',
    projectId: 'e-commerce-3d201',
    storageBucket: 'e-commerce-3d201.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBJhl5gSaFxHugmZeBPgM9lirlFK_pBxk',
    appId: '1:512210715188:web:d3c4fef4c10ee2fe3b4061',
    messagingSenderId: '512210715188',
    projectId: 'e-commerce-3d201',
    authDomain: 'e-commerce-3d201.firebaseapp.com',
    storageBucket: 'e-commerce-3d201.firebasestorage.app',
  );
}
